version: '3'
services: 
  app-db:
    image: mysql:5.7 
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - 3306:3306

    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_DATABASE=account-db
